const INIT = "INIT";
const SET_USER_NAME = "SET_USER_NAME";
const ADD_TODO_LIST = "ADD_TODO_LIST";
const UPD_TODO_LIST = "UPD_TODO_LIST";
const UPD_TODO_LISTS = "UPD_TODO_LISTS";

export { INIT, SET_USER_NAME, ADD_TODO_LIST, UPD_TODO_LIST, UPD_TODO_LISTS };
