const INIT = "INIT";
const SET_USER_NAME = "SET_USER_NAME";
const ADD_TODO_LIST = "ADD_TODO_LIST";
const UPD_TODO_LIST = "UPD_TODO_LIST";
const UPD_TODO_LISTS = "UPD_TODO_LISTS";
const SET_USER_WEATHER_FORECAST = "SET_USER_WEATHER_FORECAST";
const SET_RANDOM_QUOTATION = "SET_RANDOM_QUOTATION";
const SET_FORECAST_DAY_INDEX = "SET_FORECAST_DAY_INDEX";
const SET_FORECAST_HOUR_INDEX = "SET_FORECAST_HOUR_INDEX";

export {
  INIT,
  SET_USER_NAME,
  ADD_TODO_LIST,
  UPD_TODO_LIST,
  UPD_TODO_LISTS,
  SET_USER_WEATHER_FORECAST,
  SET_RANDOM_QUOTATION,
  SET_FORECAST_DAY_INDEX,
  SET_FORECAST_HOUR_INDEX,
};
